### ISSUE TITLE
Loading SVG page

### ISSUE THREAD

**Issue by henriquea** [christianalfoni/react-webpack-cookbook#19]
Hey @christianalfoni great work with this cookbook, it has been very useful. One thing we could add underneath "Loading LESS or SASS" is the "Loading SVG" page. 

I know we have a few ways to achieve this using with `svg-loader` but the simple way to do that is through `file-loader`.

```javascript
module: {
  loaders: [
  ...
  { 
    test: /\.svg$/, 
    loader: "file-loader" 
  },
  ...
  ]
}
```

Then in your CSS:

```css
.MyIcon {
  ...
  background-image: url(../assets/my-icon.svg);
}
```

I know I lost a few minutes yesterday looking, it might be useful for someone else as well.

Thoughts?

Cheers
